learning_rate = 0.001
loss = 'mean_squared_error'
metrics  = ['accuracy']
monitor = 'val_loss'
min_delta  = 0.05
patience = 30
epochs  = 50
train_batch_size = 128
test_batch_size = 2
steps_per_epoch=410
validation_steps = 90
image_height = 256
image_width = 256