learning_rate = 0.001
loss = 'mean_squared_error'
metrics  = ['accuracy']
monitor = 'val_loss'
min_delta  = 0
patience = 15
epochs  = 40
train_batch_size = 64
test_batch_size = 32
steps_per_epoch=800
validation_steps = 187
image_height = 256
image_width = 256