learning_rate = 0.001
loss = 'mean_squared_error'
metrics  = ['accuracy']
monitor = 'val_loss'
min_delta  = 0
patience = 2
epochs  = 5
train_batch_size = 5
test_batch_size = 2
steps_per_epoch=6
validation_steps = 5
image_height = 256
image_width = 256