learning_rate = 0.001
loss = 'mean_squared_error'
metrics  = ['accuracy']
monitor = 'val_loss'
min_delta  = 0.05
patience = 10
epochs  = 2
test_batch_size = 16
train_batch_size = 32
image_height = 256
image_width = 256